#
# Celestial Azul Light - ttk theme
#
# Generated by render.sh from the compiled GTK stylesheets. Do not edit;
# change sass/_colors.scss, run parse_sass.sh, then re-run render.sh.
#
# Colour definitions only; all widget styling lives in celestial.tcl.
# Serves both the Standard and Light Celestial modes: they differ only in
# window-manager chrome, which Tk does not draw.
#
# Tk has no alpha, so Celestial's translucent tokens arrive here already
# composited over this variant's background:
#   borders          -> #d2d2d2
#   insensitive fg   -> #878990
#   alpha(accent,.6) -> #82bee6   (GTK's notebook tab hover)
#

package require Tk 8.6

# Loadable either as an installed package or straight from the source tree.
if {[catch {package require celestial::ttk}]} {
  source [file join [file dirname [info script]] celestial.tcl]
}

namespace eval ::ttk::theme::celestial-azul-light {
  package provide ttk::theme::celestial-azul-light 1.0

  ::celestial::ttk::create celestial-azul-light [file dirname [info script]] \
    -variant azul-light -gtkcolor azul -suffix "" -colors {
      -bg          #f7f7f7
      -fg          #2b2f3b
      -text        #2e313d
      -headingfg   #555962
      -headingline #e0e0e0
      -disabledfg  #878990
      -disabledbg  #fcfcfc
      -button      #fcfcfc
      -active      #ffffff
      -inputbg     #ffffff
      -trough      #d2d2d2
      -border      #d2d2d2
      -selectbg    #3498db
      -selectfg    #ffffff
      -primary     #3498db
      -accenthover #4aa3df
      -tabhover    #82bee6
      -scrollslider #a5a7ac
      -scrollhover #babbbf
      -scaleslider #ffffff
      -progresstrough #d2d2d2
      -success     #2eb398
      -warning     #f27835
      -danger      #fc4138
    }
}
