#
# Celestial Sea Light - ttk theme
#
# Generated by render.sh from the compiled GTK stylesheets. Do not edit;
# change sass/_colors.scss, run parse_sass.sh, then re-run render.sh.
#
# Colour definitions only; all widget styling lives in celestial.tcl.
# Serves both the Standard and Light Celestial modes: they differ only in
# window-manager chrome, which Tk does not draw.
#
# Tk has no alpha, so Celestial's translucent tokens arrive here already
# composited over this variant's background:
#   borders          -> #d2d2d2
#   insensitive fg   -> #858a8c
#   alpha(accent,.6) -> #7ecebe   (GTK's notebook tab hover)
#

package require Tk 8.6

# Loadable either as an installed package or straight from the source tree.
if {[catch {package require celestial::ttk}]} {
  source [file join [file dirname [info script]] celestial.tcl]
}

namespace eval ::ttk::theme::celestial-sea-light {
  package provide ttk::theme::celestial-sea-light 1.0

  ::celestial::ttk::create celestial-sea-light [file dirname [info script]] \
    -variant sea-light -gtkcolor sea -suffix "" -colors {
      -bg          #f7f7f7
      -fg          #273134
      -text        #303d41
      -headingfg   #525a5d
      -headingline #e0e0e0
      -disabledfg  #858a8c
      -disabledbg  #fcfcfc
      -button      #fcfcfc
      -active      #ffffff
      -inputbg     #ffffff
      -trough      #d2d2d2
      -border      #d2d2d2
      -selectbg    #2eb398
      -selectfg    #ffffff
      -primary     #2eb398
      -accenthover #33c7a9
      -tabhover    #7ecebe
      -scrollslider #a4a8a9
      -scrollhover #b9bcbd
      -scaleslider #ffffff
      -progresstrough #d2d2d2
      -success     #2eb398
      -warning     #f27835
      -danger      #fc4138
    }
}
