#
# Celestial Aliz Dark - ttk theme
#
# Generated by render.sh from the compiled GTK stylesheets. Do not edit;
# change sass/_colors.scss, run parse_sass.sh, then re-run render.sh.
#
# Colour definitions only; all widget styling lives in celestial.tcl.
#
# Tk has no alpha, so Celestial's translucent tokens arrive here already
# composited over this variant's background:
#   borders          -> #1a1a1a
#   insensitive fg   -> #6e6969
#   alpha(accent,.6) -> #9e403b   (GTK's notebook tab hover)
#

package require Tk 8.6

# Loadable either as an installed package or straight from the source tree.
if {[catch {package require celestial::ttk}]} {
  source [file join [file dirname [info script]] celestial.tcl]
}

namespace eval ::ttk::theme::celestial-aliz-dark {
  package provide ttk::theme::celestial-aliz-dark 1.0

  ::celestial::ttk::create celestial-aliz-dark [file dirname [info script]] \
    -variant aliz-dark -gtkcolor aliz -suffix -dark -colors {
      -bg          #222222
      -fg          #cbbfbf
      -text        #b5abab
      -headingfg   #aaa0a0
      -headingline #404040
      -disabledfg  #6e6969
      -disabledbg  #272727
      -button      #2b2b2b
      -active      #404040
      -inputbg     #262626
      -trough      #1a1a1a
      -border      #1a1a1a
      -selectbg    #f0544c
      -selectfg    #ffffff
      -primary     #f0544c
      -accenthover #f26a64
      -tabhover    #9e403b
      -scrollslider #666161
      -scrollhover #555151
      -scaleslider #ffffff
      -progresstrough #151515
      -success     #3498db
      -warning     #f27835
      -danger      #fc4138
    }
}
