#
# Celestial Azul Dark - ttk theme
#
# Generated by render.sh from the compiled GTK stylesheets. Do not edit;
# change sass/_colors.scss, run parse_sass.sh, then re-run render.sh.
#
# Colour definitions only; all widget styling lives in celestial.tcl.
#
# Tk has no alpha, so Celestial's translucent tokens arrive here already
# composited over this variant's background:
#   borders          -> #14161b
#   insensitive fg   -> #63686e
#   alpha(accent,.6) -> #2a6792   (GTK's notebook tab hover)
#

package require Tk 8.6

# Loadable either as an installed package or straight from the source tree.
if {[catch {package require celestial::ttk}]} {
  source [file join [file dirname [info script]] celestial.tcl]
}

namespace eval ::ttk::theme::celestial-azul-dark {
  package provide ttk::theme::celestial-azul-dark 1.0

  ::celestial::ttk::create celestial-azul-dark [file dirname [info script]] \
    -variant azul-dark -gtkcolor azul -suffix -dark -colors {
      -bg          #1b1d24
      -fg          #bbc3c8
      -text        #afb4ba
      -headingfg   #9ca3a9
      -headingline #3d3f45
      -disabledfg  #63686e
      -disabledbg  #1f222a
      -button      #262a32
      -active      #383d49
      -inputbg     #22252c
      -trough      #14161b
      -border      #14161b
      -selectbg    #3498db
      -selectfg    #ffffff
      -primary     #3498db
      -accenthover #4aa3df
      -tabhover    #2a6792
      -scrollslider #5b5f66
      -scrollhover #4b4f55
      -scaleslider #ffffff
      -progresstrough #101115
      -success     #2eb398
      -warning     #f27835
      -danger      #fc4138
    }
}
