#
# Celestial Sea Dark - ttk theme
#
# Generated by render.sh from the compiled GTK stylesheets. Do not edit;
# change sass/_colors.scss, run parse_sass.sh, then re-run render.sh.
#
# Colour definitions only; all widget styling lives in celestial.tcl.
#
# Tk has no alpha, so Celestial's translucent tokens arrive here already
# composited over this variant's background:
#   borders          -> #141a1b
#   insensitive fg   -> #6b7373
#   alpha(accent,.6) -> #26796a   (GTK's notebook tab hover)
#

package require Tk 8.6

# Loadable either as an installed package or straight from the source tree.
if {[catch {package require celestial::ttk}]} {
  source [file join [file dirname [info script]] celestial.tcl]
}

namespace eval ::ttk::theme::celestial-sea-dark {
  package provide ttk::theme::celestial-sea-dark 1.0

  ::celestial::ttk::create celestial-sea-dark [file dirname [info script]] \
    -variant sea-dark -gtkcolor sea -suffix -dark -colors {
      -bg          #1b2224
      -fg          #ccd7d4
      -text        #abb9b6
      -headingfg   #aab5b3
      -headingline #3d4447
      -disabledfg  #6b7373
      -disabledbg  #1f282a
      -button      #263034
      -active      #38464b
      -inputbg     #222b2e
      -trough      #141a1b
      -border      #141a1b
      -selectbg    #2eb398
      -selectfg    #ffffff
      -primary     #2eb398
      -accenthover #33c7a9
      -tabhover    #26796a
      -scrollslider #626a6a
      -scrollhover #505859
      -scaleslider #ffffff
      -progresstrough #101415
      -success     #2eb398
      -warning     #f27835
      -danger      #fc4138
    }
}
