#
# Celestial Pueril Light - ttk theme
#
# Generated by render.sh from the compiled GTK stylesheets. Do not edit;
# change sass/_colors.scss, run parse_sass.sh, then re-run render.sh.
#
# Colour definitions only; all widget styling lives in celestial.tcl.
# Serves both the Standard and Light Celestial modes: they differ only in
# window-manager chrome, which Tk does not draw.
#
# Tk has no alpha, so Celestial's translucent tokens arrive here already
# composited over this variant's background:
#   borders          -> #d2d2d2
#   insensitive fg   -> #8b8b8b
#   alpha(accent,.6) -> #bdd3a7   (GTK's notebook tab hover)
#

package require Tk 8.6

# Loadable either as an installed package or straight from the source tree.
if {[catch {package require celestial::ttk}]} {
  source [file join [file dirname [info script]] celestial.tcl]
}

namespace eval ::ttk::theme::celestial-pueril-light {
  package provide ttk::theme::celestial-pueril-light 1.0

  ::celestial::ttk::create celestial-pueril-light [file dirname [info script]] \
    -variant pueril-light -gtkcolor pueril -suffix "" -colors {
      -bg          #f7f7f7
      -fg          #323232
      -text        #363636
      -headingfg   #5b5b5b
      -headingline #e0e0e0
      -disabledfg  #8b8b8b
      -disabledbg  #fcfcfc
      -button      #fcfcfc
      -active      #ffffff
      -inputbg     #ffffff
      -trough      #d2d2d2
      -border      #d2d2d2
      -selectbg    #97bb72
      -selectfg    #ffffff
      -primary     #97bb72
      -accenthover #a4c383
      -tabhover    #bdd3a7
      -scrollslider #a8a8a8
      -scrollhover #bcbcbc
      -scaleslider #ffffff
      -progresstrough #d2d2d2
      -success     #3498db
      -warning     #f27835
      -danger      #fc4138
    }
}
