# Celestial ttk themes.
#
# Generated by render.sh. Do not edit.
#
# Registering each variant as a package is what makes the global X resource
# path work: ttk::DefaultTheme reads *TkTheme from the option database and
# does 'package require ttk::theme::<name>', so every Tk app picks the theme
# up with no per-application opt-in.
#
# Requires this directory on Tcl's auto_path: a system-wide install under
# /usr/lib, or TCLLIBPATH for a per-user one.

package ifneeded celestial::ttk 1.0 \
  [list source [file join $dir celestial.tcl]]

package ifneeded ttk::theme::celestial-sea-light 1.0 \
  [list source [file join $dir celestial-sea-light.tcl]]

package ifneeded ttk::theme::celestial-sea-dark 1.0 \
  [list source [file join $dir celestial-sea-dark.tcl]]

package ifneeded ttk::theme::celestial-aliz-light 1.0 \
  [list source [file join $dir celestial-aliz-light.tcl]]

package ifneeded ttk::theme::celestial-aliz-dark 1.0 \
  [list source [file join $dir celestial-aliz-dark.tcl]]

package ifneeded ttk::theme::celestial-azul-light 1.0 \
  [list source [file join $dir celestial-azul-light.tcl]]

package ifneeded ttk::theme::celestial-azul-dark 1.0 \
  [list source [file join $dir celestial-azul-dark.tcl]]

package ifneeded ttk::theme::celestial-pueril-light 1.0 \
  [list source [file join $dir celestial-pueril-light.tcl]]

package ifneeded ttk::theme::celestial-pueril-dark 1.0 \
  [list source [file join $dir celestial-pueril-dark.tcl]]
