[General]
alt_bg=#eeeeee
bg=#f7f7f7
css=
css_template_sel=items
cur_item_css=\
    ;padding: 0.3em\
    ;background: ${sel_bg}
edit_bg=#ffffff
edit_fg=#2d2d2d
edit_font="Sans,11,-1,5,50,0,0,0,0,0"
fg=#2d2d2d
find_bg=#eeeeee
find_fg=#2d2d2d
find_font="Sans,10,-1,5,50,0,0,0,0,0"
font="Sans,10,-1,5,50,0,0,0,0,0"
font_antialiasing=true
hover_item_css=
icon_size=16
item_css=
item_spacing=
menu_bar_css=\
    ;background: ${bg}\
    ;color: ${fg}
menu_bar_selected_css=\
    ;background: ${sel_bg}\
    ;color: ${sel_fg}
menu_bar_disabled_css=\
    ;color: ${fg + #999}
menu_css=\
    ;background: ${bg}\
    ;color: ${fg}
notes_bg=#ffffff
notes_css=
notes_fg=#2d2d2d
notes_font="Sans,11,-1,5,50,0,0,0,0,0"
notification_bg=#f7f7f7
notification_fg=#2d2d2d
notification_font=
num_fg=#666666
num_font="Sans,7,-1,5,25,0,0,0,0,0"
search_bg=#eeeeee
search_fg=#2d2d2d
sel_bg=#3498db
sel_fg=#ffffff
show_number=true
show_scrollbars=true
style_main_window=false
tab_bar_css=\
    ;background: ${bg}
tab_bar_item_css=\
    ;color: ${fg + #333}\
    ;background: ${bg - #111}\
    ;border: none\
    ;padding: 0.3em
tab_bar_scroll_buttons_css=\
    ;background: ${bg - #222}\
    ;border: none\
    ;color: ${fg}
tab_bar_sel_item_css=\
    ;background: ${sel_bg}\
    ;color: ${sel_fg}\
    ;border: none\
    ;padding: 0.3em
tab_tree_css=\
    ;color: ${fg}\
    ;background-color: ${bg}
tab_tree_item_css=\
    ;padding: 0.3em
tab_tree_sel_item_css=\
    ;background: ${sel_bg}\
    ;color: ${sel_fg}
tool_bar_css=\
    ;background: ${bg}\
    ;color: ${fg}
tool_button_css=\
    ;background: transparent\
    ;border: none\
    ;color: ${fg}\
    ;padding: 0.2em
use_system_icons=false
theme_color=#3498db
