[General]
alt_bg=#2d2d30
bg=#222222
css=
css_template_sel=items
cur_item_css=\
    ;padding: 0.3em\
    ;background: ${sel_bg}
edit_bg=#222222
edit_fg=#d8d8d8
edit_font="Sans,11,-1,5,50,0,0,0,0,0"
fg=#d8d8d8
find_bg=#3d3d40
find_fg=#d8d8d8
find_font="Sans,10,-1,5,50,0,0,0,0,0"
font="Sans,10,-1,5,50,0,0,0,0,0"
font_antialiasing=true
hover_item_css=
icon_size=16
item_css=
item_spacing=
menu_bar_css=\
    ;background: ${bg}\
    ;color: ${fg}
menu_bar_selected_css=\
    ;background: ${sel_bg}\
    ;color: ${fg}
menu_bar_disabled_css=\
    ;color: ${fg - #666}
menu_css=\
    ;background: ${bg}\
    ;color: ${fg}
notes_bg=#2d2d30
notes_css=
notes_fg=#d8d8d8
notes_font="Sans,11,-1,5,50,0,0,0,0,0"
notification_bg=#222222
notification_fg=#d8d8d8
notification_font=
num_fg=#b0b0b0
num_font="Sans,7,-1,5,25,0,0,0,0,0"
search_bg=#2d2d30
search_fg=#d8d8d8
sel_bg=#97bb72
sel_fg=#ffffff
show_number=true
show_scrollbars=true
style_main_window=false
tab_bar_css=\
    ;background: ${bg}
tab_bar_item_css=\
    ;color: ${fg - #222}\
    ;background: ${bg + #111}\
    ;border: none\
    ;padding: 0.3em
tab_bar_scroll_buttons_css=\
    ;background: ${bg + #222}\
    ;border: none\
    ;color: ${fg}
tab_bar_sel_item_css=\
    ;background: ${sel_bg}\
    ;color: ${sel_fg}\
    ;border: none\
    ;padding: 0.3em
tab_tree_css=\
    ;color: ${fg}\
    ;background-color: ${bg}
tab_tree_item_css=\
    ;padding: 0.3em
tab_tree_sel_item_css=\
    ;background: ${sel_bg}\
    ;color: ${sel_fg}
tool_bar_css=\
    ;background: ${bg}\
    ;color: ${fg}
tool_button_css=\
    ;background: transparent\
    ;border: none\
    ;color: ${fg}\
    ;padding: 0.2em
use_system_icons=false
theme_color=#97bb72
