background            #000000
background_opacity    0.85
foreground            #cfdcd8
cursor                #7e8e8c
selection_background  #3d4d4f
selection_foreground  #ffffff
color0                #2a2a2a
color8                #7e8e8c
color1                #f0544c
color9                #e74c3c
color2                #2eb398
color10               #2eb398
color3                #F39C12
color11               #f5b041
color4                #3498db
color12               #5ba3e0
color5                #c678dd
color13               #d291e6
color6                #42A5F5
color14               #6dd4f7
color7                #cfdcd8
color15               #ffffff
